// JavaScript Document

{
	"kind": "Listing",
	"data": {
		"modhash": "1w3zaalpeqd87dfb491a6bba2f11901818954a287fdce17e67",
		"children": [{
			"kind": "t1",
			"data": {
				"body": "this was not a joke :D",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jldma",
				"created": 1315960400.0,
				"dest": "GavChap",
				"author": "Markulatura",
				"created_utc": 1315935200.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>this was not a joke :D</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26275173722,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jldma?context=3",
				"replies": "",
				"new": false,
				"id": "c2jldma",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Might want to look at how Spaz allows different themes as a starting point",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jk4w5",
				"created": 1315951850.0,
				"dest": "GavChap",
				"author": "RyanMacG",
				"created_utc": 1315926650.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Might want to look at how Spaz allows different themes as a starting point</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274886059,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jk4w5?context=3",
				"replies": "",
				"new": false,
				"id": "c2jk4w5",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Don't suppose you'd consider a Pre app? More specifically one that worked on the Pre3? I'd be willing to contribute :P",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jk28p",
				"created": 1315951307.0,
				"dest": "GavChap",
				"author": "RyanMacG",
				"created_utc": 1315926107.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Don't suppose you'd consider a Pre app? More specifically one that worked on the Pre3? I'd be willing to contribute :P</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jk28p?context=3",
				"replies": "",
				"new": false,
				"id": "c2jk28p",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "will you be making this upgradeable through preware?",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jjteq",
				"created": 1315949376.0,
				"dest": "GavChap",
				"author": "burntcookie90",
				"created_utc": 1315924176.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>will you be making this upgradeable through preware?</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jjteq?context=3",
				"replies": "",
				"new": false,
				"id": "c2jjteq",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "one more think i would like:  A \"Open link in browser\" function or a share function. IMO the first one is enough, so you can copy-paste the URL. If you also think this is a good idea, i would place it next to the \"comments\" button. a good icon would be a globe :)",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jjl9s",
				"created": 1315947371.0,
				"dest": "GavChap",
				"author": "Markulatura",
				"created_utc": 1315922171.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>one more think i would like:  A \"Open link in browser\" function or a share function. IMO the first one is enough, so you can copy-paste the URL. If you also think this is a good idea, i would place it next to the \"comments\" button. a good icon would be a globe :)</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26275139121,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jjl9s?context=3",
				"replies": "",
				"new": false,
				"id": "c2jjl9s",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Maybe some more suggestions (im working as a software tester, sorry :D)\n\n- Why a Wine-Red interface? It conflict with the blue karma-boxes and URLs. \n\nFeature Request:\n-Mark visited links. Is this possible? It would be enough if the URL would change to purple like with every browser on the planet (exept TP Browser...)\n\nI'm at work atm, will take a deeper look at the app on my way home and send you some more feedback.\n",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jjb33",
				"created": 1315944483.0,
				"dest": "GavChap",
				"author": "Markulatura",
				"created_utc": 1315919283.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Maybe some more suggestions (im working as a software tester, sorry :D)</p>\n\n<ul>\n<li>Why a Wine-Red interface? It conflict with the blue karma-boxes and URLs.</li>\n</ul>\n\n\n<p>Feature Request:\n-Mark visited links. Is this possible? It would be enough if the URL would change to purple like with every browser on the planet (exept TP Browser...)</p>\n\n<p>I'm at work atm, will take a deeper look at the app on my way home and send you some more feedback.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jjb33?context=3",
				"replies": "",
				"new": false,
				"id": "c2jjb33",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "i think i fell in love with you. Finally a usable reddit app on my TP =)\n\ntaking donations? Coffee? Pizza? Anything? ",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jj9gn",
				"created": 1315943951.0,
				"dest": "GavChap",
				"author": "Markulatura",
				"created_utc": 1315918751.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>i think i fell in love with you. Finally a usable reddit app on my TP =)</p>\n\n<p>taking donations? Coffee? Pizza? Anything?</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26275115143,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jj9gn?context=3",
				"replies": "",
				"new": false,
				"id": "c2jj9gn",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "It's really only an issue when I'm on the 3rd page browsing and I upvote a submission.  Then I get brought back to page 1 and I have to scroll down and wait for 2 more pages to load just to get back to where I was.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jj0al",
				"created": 1315940401.0,
				"dest": "GavChap",
				"author": "soulblow",
				"created_utc": 1315915201.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>It's really only an issue when I'm on the 3rd page browsing and I upvote a submission.  Then I get brought back to page 1 and I have to scroll down and wait for 2 more pages to load just to get back to where I was.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26275119667,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jj0al?context=3",
				"replies": "",
				"new": false,
				"id": "c2jj0al",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "I'm not sure if anybody mentioned this yet.  But every time I upvote/downvote.  It refreshes the list of posts and brings me back to the top of the the front page.  ",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jizbp",
				"created": 1315939907.0,
				"dest": "GavChap",
				"author": "soulblow",
				"created_utc": 1315914707.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>I'm not sure if anybody mentioned this yet.  But every time I upvote/downvote.  It refreshes the list of posts and brings me back to the top of the the front page.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jizbp?context=3",
				"replies": "",
				"new": false,
				"id": "c2jizbp",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "IMPLEMENT IT AND TAKE ALL MY MONEYZ!!!",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jiwgu",
				"created": 1315938395.0,
				"dest": "GavChap",
				"author": "Markulatura",
				"created_utc": 1315913195.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>IMPLEMENT IT AND TAKE ALL MY MONEYZ!!!</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26275099368,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jiwgu?context=3",
				"replies": "",
				"new": false,
				"id": "c2jiwgu",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "I'm at work and could not check your app atm, but i hope you have a feature, which any other reddit app is missing: \n\nCan I switch to /r/all? Every fucking app have only the possibility to go to /r/, but i want to go to the real frontpage!",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jik3v",
				"created": 1315930326.0,
				"dest": "GavChap",
				"author": "Markulatura",
				"created_utc": 1315905126.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>I'm at work and could not check your app atm, but i hope you have a feature, which any other reddit app is missing:</p>\n\n<p>Can I switch to /r/all? Every fucking app have only the possibility to go to /r/, but i want to go to the real frontpage!</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jik3v?context=3",
				"replies": "",
				"new": false,
				"id": "c2jik3v",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Great app man, your the best. I've been waiting for a good reddit app and this is it. My biggest nitpick (only constructive criticism, you've done a great job) is that I hated using the browser because after every link I clicked , when I went back it always put me at the top of the page, yours only does this when I upvote   something which isn't as often as clicking a link ",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jhnb2",
				"created": 1315916932.0,
				"dest": "GavChap",
				"author": "advanced4",
				"created_utc": 1315891732.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Great app man, your the best. I've been waiting for a good reddit app and this is it. My biggest nitpick (only constructive criticism, you've done a great job) is that I hated using the browser because after every link I clicked , when I went back it always put me at the top of the page, yours only does this when I upvote   something which isn't as often as clicking a link</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jhnb2?context=3",
				"replies": "",
				"new": false,
				"id": "c2jhnb2",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "fast....I was wondering, is there a way to add new reddits?",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jhgc0",
				"created": 1315915185.0,
				"dest": "GavChap",
				"author": "brf4n",
				"created_utc": 1315889985.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>fast....I was wondering, is there a way to add new reddits?</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jhgc0?context=3",
				"replies": "",
				"new": false,
				"id": "c2jhgc0",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Cyanogenmod works pretty well on a larger screen with Gingerbread.  WebOS and Android and iOS are all just overblown smartphone OSes that have been tweaked for higher resolutions on tablets.  Honeycomb isn't really that different from Gingerbread underneath.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jh3hd",
				"created": 1315912300.0,
				"dest": "GavChap",
				"author": "btdonovan",
				"created_utc": 1315887100.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Cyanogenmod works pretty well on a larger screen with Gingerbread.  WebOS and Android and iOS are all just overblown smartphone OSes that have been tweaked for higher resolutions on tablets.  Honeycomb isn't really that different from Gingerbread underneath.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274074058,
				"context": "/r/webos/comments/kay86/if_you_love_your_touchpad_remember_that_the_best/c2jh3hd?context=3",
				"replies": "",
				"new": false,
				"id": "c2jh3hd",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Wow! Very nice. My new favorite reddit app. Thanks! Keep up the good work.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jgl9m",
				"created": 1315908607.0,
				"dest": "GavChap",
				"author": "gmauler",
				"created_utc": 1315883407.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Wow! Very nice. My new favorite reddit app. Thanks! Keep up the good work.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jgl9m?context=3",
				"replies": "",
				"new": false,
				"id": "c2jgl9m",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Wow! Very nice. My new favorite reddit app. Thanks! Keep up the good work.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jgk5g",
				"created": 1315908398.0,
				"dest": "GavChap",
				"author": "gmauler",
				"created_utc": 1315883198.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Wow! Very nice. My new favorite reddit app. Thanks! Keep up the good work.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jgk5g?context=3",
				"replies": "",
				"new": false,
				"id": "c2jgk5g",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Nailed it.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jgeuz",
				"created": 1315907332.0,
				"dest": "GavChap",
				"author": "FooFighter828",
				"created_utc": 1315882132.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Nailed it.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jgeuz?context=3",
				"replies": "",
				"new": false,
				"id": "c2jgeuz",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "just noticed a bug. When typing a comment, if its longer than the box allows, instead of scrolling the typed words appear over the vote buttons and continue down the screen. Thanks again",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jgcv2",
				"created": 1315906918.0,
				"dest": "GavChap",
				"author": "adamthinks",
				"created_utc": 1315881718.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>just noticed a bug. When typing a comment, if its longer than the box allows, instead of scrolling the typed words appear over the vote buttons and continue down the screen. Thanks again</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jgcv2?context=3",
				"replies": "",
				"new": false,
				"id": "c2jgcv2",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "I'm having the same issue. I'm subscribed to maybe 30 subreddits and only 20 or so show up. I use reddit is fun, baconreader, and now reddionic on android and all my subreddits show up on them.\nThis is a great app though, thanks for taking the time to make it, much appreciated!",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jg7ja",
				"created": 1315905871.0,
				"dest": "GavChap",
				"author": "adamthinks",
				"created_utc": 1315880671.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>I'm having the same issue. I'm subscribed to maybe 30 subreddits and only 20 or so show up. I use reddit is fun, baconreader, and now reddionic on android and all my subreddits show up on them.\nThis is a great app though, thanks for taking the time to make it, much appreciated!</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274860179,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jg7ja?context=3",
				"replies": "",
				"new": false,
				"id": "c2jg7ja",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "This is delicious.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jg16t",
				"created": 1315879302.0,
				"dest": "GavChap",
				"author": "burntcookie90",
				"created_utc": 1315879302.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>This is delicious.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jg16t?context=3",
				"replies": "",
				"new": false,
				"id": "c2jg16t",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Awesome. Many thanks for not only this app, but for your work helping to keep WebOS alive and kicking!",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jfakq",
				"created": 1315898691.0,
				"dest": "GavChap",
				"author": "adssse",
				"created_utc": 1315873491.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Awesome. Many thanks for not only this app, but for your work helping to keep WebOS alive and kicking!</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jfakq?context=3",
				"replies": "",
				"new": false,
				"id": "c2jfakq",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Just had a look at the latest version, great stuff! Congratulation! ;-)",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jf7lm",
				"created": 1315872869.0,
				"dest": "GavChap",
				"author": "mefm247",
				"created_utc": 1315872869.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Just had a look at the latest version, great stuff! Congratulation! ;-)</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274884851,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jf7lm?context=3",
				"replies": "",
				"new": false,
				"id": "c2jf7lm",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "If you like the name, I can get my art director to design a logo for the application. ;-)",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jf621",
				"created": 1315897749.0,
				"dest": "GavChap",
				"author": "mefm247",
				"created_utc": 1315872549.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>If you like the name, I can get my art director to design a logo for the application. ;-)</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274861827,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jf621?context=3",
				"replies": "",
				"new": false,
				"id": "c2jf621",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "You plan to submit this to the webos app market eventually or just submit to the homebrew channel?",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jeseq",
				"created": 1315894856.0,
				"dest": "GavChap",
				"author": "llamabox",
				"created_utc": 1315869656.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>You plan to submit this to the webos app market eventually or just submit to the homebrew channel?</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jeseq?context=3",
				"replies": "",
				"new": false,
				"id": "c2jeseq",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "My initial thoughts on it:\n- I like the looks and functionality of it. The red could be toned down a bit to a bit more neutral color as my eyes seem to get drawn to it.\n- I like how you can collapse each pane like the email. I don't know of it is possible not to let the user set their preference for how wide they want each pane. It looks fine landscape but I usually use my touch pad in a portrait type manner and would like the option to have the open story wider than the link list.\n- While typing this reply, I noticed that the text box for replies doesn't scroll or extend for longer replies, so the ok and cancel buttons get covered with text.\nAwesome job with the project though! I give you major credit. Thanks.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jes19",
				"created": 1315894776.0,
				"dest": "GavChap",
				"author": "firecracker1",
				"created_utc": 1315869576.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>My initial thoughts on it:\n- I like the looks and functionality of it. The red could be toned down a bit to a bit more neutral color as my eyes seem to get drawn to it.\n- I like how you can collapse each pane like the email. I don't know of it is possible not to let the user set their preference for how wide they want each pane. It looks fine landscape but I usually use my touch pad in a portrait type manner and would like the option to have the open story wider than the link list.\n- While typing this reply, I noticed that the text box for replies doesn't scroll or extend for longer replies, so the ok and cancel buttons get covered with text.\nAwesome job with the project though! I give you major credit. Thanks.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jes19?context=3",
				"replies": "",
				"new": false,
				"id": "c2jes19",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Thanks!",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jeq9s",
				"created": 1315894415.0,
				"dest": "GavChap",
				"author": "bbene",
				"created_utc": 1315869215.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Thanks!</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274884851,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jeq9s?context=3",
				"replies": "",
				"new": false,
				"id": "c2jeq9s",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "I've got preware installed and running but I'm having trouble downloading and installing this. So far I've tried clicking the links above directly within my Touchpad browser. I've also tried the Dropbox method listed lower down on this thread. Any other ideas?\n\nThe direct links go to a page with scrambled text. The Dropbox method launches Preware but gives and error when I try to install.\n\nMy Touchpad is updated to the latest system update.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jek4b",
				"created": 1315893090.0,
				"dest": "GavChap",
				"author": "grimdeath",
				"created_utc": 1315867890.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>I've got preware installed and running but I'm having trouble downloading and installing this. So far I've tried clicking the links above directly within my Touchpad browser. I've also tried the Dropbox method listed lower down on this thread. Any other ideas?</p>\n\n<p>The direct links go to a page with scrambled text. The Dropbox method launches Preware but gives and error when I try to install.</p>\n\n<p>My Touchpad is updated to the latest system update.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jek4b?context=3",
				"replies": "",
				"new": false,
				"id": "c2jek4b",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "This is really great.  Amazing for a 1.0.1 version actually.  Here are a few of my quick requests:\n\n* Mark the link as read somehow.  Perhaps, change the blue link to light blue or gray?\n* Any way to make the list of links smaller to give more real estate to the web/comments?  Maybe make that adjustable somehow, because even with the left panel collapsed it leaves very little room for webpages/imgur/comments.  Having to resize the panel for every click is a bit much.\n\nReally outstanding work so far.  Sell this on the market and I will definitely pay for it.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jeegi",
				"created": 1315891911.0,
				"dest": "GavChap",
				"author": "g-funkster",
				"created_utc": 1315866711.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>This is really great.  Amazing for a 1.0.1 version actually.  Here are a few of my quick requests:</p>\n\n<ul>\n<li>Mark the link as read somehow.  Perhaps, change the blue link to light blue or gray?</li>\n<li>Any way to make the list of links smaller to give more real estate to the web/comments?  Maybe make that adjustable somehow, because even with the left panel collapsed it leaves very little room for webpages/imgur/comments.  Having to resize the panel for every click is a bit much.</li>\n</ul>\n\n\n<p>Really outstanding work so far.  Sell this on the market and I will definitely pay for it.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jeegi?context=3",
				"replies": "",
				"new": false,
				"id": "c2jeegi",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "It wouldn't download for me, each of the links above when clicked tried to render as text.\n\nSo with Dropbox on my computer, I:\n\n* I saved it to my Dropbox/Public folder\n* Right-clicked on it -> dropbox menu -> copy public url\n* email the url to yourself or just type it into your touchpad's browser manually\n\nThen the preware installer came up.\n\nShameless plug! If you don't have Dropbox and you are now going to install it (and you appreciate my instructions!) please sign up with this referral link, it will give both of us extra space: [Join Dropbox](http://db.tt/NdkirSi)",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jeb5n",
				"created": 1315891246.0,
				"dest": "GavChap",
				"author": "g-funkster",
				"created_utc": 1315866046.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>It wouldn't download for me, each of the links above when clicked tried to render as text.</p>\n\n<p>So with Dropbox on my computer, I:</p>\n\n<ul>\n<li>I saved it to my Dropbox/Public folder</li>\n<li>Right-clicked on it -> dropbox menu -> copy public url</li>\n<li>email the url to yourself or just type it into your touchpad's browser manually</li>\n</ul>\n\n\n<p>Then the preware installer came up.</p>\n\n<p>Shameless plug! If you don't have Dropbox and you are now going to install it (and you appreciate my instructions!) please sign up with this referral link, it will give both of us extra space: <a href=\"http://db.tt/NdkirSi\" >Join Dropbox</a></p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jeb5n?context=3",
				"replies": "",
				"new": false,
				"id": "c2jeb5n",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "at least sixty.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2je6r2",
				"created": 1315865163.0,
				"dest": "GavChap",
				"author": "ebonwumon",
				"created_utc": 1315865163.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>at least sixty.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274860179,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2je6r2?context=3",
				"replies": "",
				"new": false,
				"id": "c2je6r2",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "SOMEONE DESIGN IT FOR THIS MAN ASAP ",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2je46o",
				"created": 1315889867.0,
				"dest": "GavChap",
				"author": "diamond_dobby",
				"created_utc": 1315864667.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>SOMEONE DESIGN IT FOR THIS MAN ASAP</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274861827,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2je46o?context=3",
				"replies": "",
				"new": false,
				"id": "c2je46o",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Thanks",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2je2jz",
				"created": 1315889542.0,
				"dest": "GavChap",
				"author": "JavaLSU",
				"created_utc": 1315864342.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Thanks</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274884486,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2je2jz?context=3",
				"replies": "",
				"new": false,
				"id": "c2je2jz",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Nice",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2je2ao",
				"created": 1315889494.0,
				"dest": "GavChap",
				"author": "JavaLSU",
				"created_utc": 1315864294.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Nice</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274884851,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2je2ao?context=3",
				"replies": "",
				"new": false,
				"id": "c2je2ao",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "All we need now is a night friendly version :) Black stylesheet should do the trick",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jdz70",
				"created": 1315888914.0,
				"dest": "GavChap",
				"author": "enabled",
				"created_utc": 1315863714.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>All we need now is a night friendly version :) Black stylesheet should do the trick</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jdz70?context=3",
				"replies": "",
				"new": false,
				"id": "c2jdz70",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "404 error :(",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jdua0",
				"created": 1315888000.0,
				"dest": "GavChap",
				"author": "JavaLSU",
				"created_utc": 1315862800.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>404 error :(</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274867188,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jdua0?context=3",
				"replies": "",
				"new": false,
				"id": "c2jdua0",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Are you using drawer controls?",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jdrur",
				"created": 1315887546.0,
				"dest": "GavChap",
				"author": "krische",
				"created_utc": 1315862346.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Are you using drawer controls?</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274842730,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jdrur?context=3",
				"replies": "",
				"new": false,
				"id": "c2jdrur",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "I also think you should name it AlienChap. ;-)",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jdfvt",
				"created": 1315885191.0,
				"dest": "GavChap",
				"author": "mefm247",
				"created_utc": 1315859991.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>I also think you should name it AlienChap. ;-)</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274834673,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jdfvt?context=3",
				"replies": "",
				"new": false,
				"id": "c2jdfvt",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "There's a problem with the subreddit list - its the same problem the author of red it 2 had with the reddit API. Basically, the subreddit list on the left is a random  selection of the subreddits you're currently subscribed to, but not all of them. There is no way to view all of them in this reddit app, nor is there a way to manually enter a subreddit name. Leads to an annoying situation.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jddic",
				"created": 1315859551.0,
				"dest": "GavChap",
				"author": "ebonwumon",
				"created_utc": 1315859551.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>There's a problem with the subreddit list - its the same problem the author of red it 2 had with the reddit API. Basically, the subreddit list on the left is a random  selection of the subreddits you're currently subscribed to, but not all of them. There is no way to view all of them in this reddit app, nor is there a way to manually enter a subreddit name. Leads to an annoying situation.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jddic?context=3",
				"replies": "",
				"new": false,
				"id": "c2jddic",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Thats good to know. Keep up the good work.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jdcww",
				"created": 1315884637.0,
				"dest": "GavChap",
				"author": "gergtreble",
				"created_utc": 1315859437.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Thats good to know. Keep up the good work.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274842730,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jdcww?context=3",
				"replies": "",
				"new": false,
				"id": "c2jdcww",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "JavaLSU said exactly what I meant!\n\nOnce again great work GavChap.\n\nAnd my final suggestions for now:\n\n\nInstead of including a back and forward buttons at the bottom which is the space you have assigned for the reddit functions (comments/etc), I would create a separate toolbar at the top of the content being displayed that would contain the following functions: Back,Forward,Refresh, Title, and a share button which would allow us to send the link by email and would also give a \"Open in the browser\" and \"copy URL\" option. One important thing about this bar, unlike the bottom bar that never moves, this bar would scroll with the content the same way that the \"Safari\" (from the iPhone) bar moves with the content. And then since you've made some space in the bottom bar, you could then include Previous and Next buttons which would allow us to move from one post to another without needing to have the list open. This would allow for the BEST full screen view possible.\n\n\nAnother idea but this is more for a future version, would be to automatically show the post list to the left when browsing the comments (this would make the comments look better as you wouldn't have a super long line which is harder to read), but additionally you would have the perfect reading workflow for full screen reading. Ie. I'm looking at a post in full screen (no list to the left, just the link in full), I then check out the comments, by checking out the comments I can now click on the next link on the left without having to re-open the post list. So the workflow becomes: View post, look at commments, select new post, view post, look at comments, etc. The list of posts dissapears again when you select a new post.\n\n\nThanks again for the great app and it's already my main reddit app despite still being an alpha.\n\nCheers",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jdbs0",
				"created": 1315884438.0,
				"dest": "GavChap",
				"author": "mefm247",
				"created_utc": 1315859238.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>JavaLSU said exactly what I meant!</p>\n\n<p>Once again great work GavChap.</p>\n\n<p>And my final suggestions for now:</p>\n\n<p>Instead of including a back and forward buttons at the bottom which is the space you have assigned for the reddit functions (comments/etc), I would create a separate toolbar at the top of the content being displayed that would contain the following functions: Back,Forward,Refresh, Title, and a share button which would allow us to send the link by email and would also give a \"Open in the browser\" and \"copy URL\" option. One important thing about this bar, unlike the bottom bar that never moves, this bar would scroll with the content the same way that the \"Safari\" (from the iPhone) bar moves with the content. And then since you've made some space in the bottom bar, you could then include Previous and Next buttons which would allow us to move from one post to another without needing to have the list open. This would allow for the BEST full screen view possible.</p>\n\n<p>Another idea but this is more for a future version, would be to automatically show the post list to the left when browsing the comments (this would make the comments look better as you wouldn't have a super long line which is harder to read), but additionally you would have the perfect reading workflow for full screen reading. Ie. I'm looking at a post in full screen (no list to the left, just the link in full), I then check out the comments, by checking out the comments I can now click on the next link on the left without having to re-open the post list. So the workflow becomes: View post, look at commments, select new post, view post, look at comments, etc. The list of posts dissapears again when you select a new post.</p>\n\n<p>Thanks again for the great app and it's already my main reddit app despite still being an alpha.</p>\n\n<p>Cheers</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274834673,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jdbs0?context=3",
				"replies": "",
				"new": false,
				"id": "c2jdbs0",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "I might be being a bit dumb but is there a way to dl the ipk directly on my touchpad ",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jd661",
				"created": 1315883363.0,
				"dest": "GavChap",
				"author": "frantwo",
				"created_utc": 1315858163.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>I might be being a bit dumb but is there a way to dl the ipk directly on my touchpad</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jd661?context=3",
				"replies": "",
				"new": false,
				"id": "c2jd661",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "I might be being a bit dumb but is there a way to dl the ipk directly on my touchpad ",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jd65k",
				"created": 1315883360.0,
				"dest": "GavChap",
				"author": "frantwo",
				"created_utc": 1315858160.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>I might be being a bit dumb but is there a way to dl the ipk directly on my touchpad</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jd65k?context=3",
				"replies": "",
				"new": false,
				"id": "c2jd65k",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "All I want is collapsable comment trees! None of the (otherwise awesome) reddit apps can do this!",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jd0qi",
				"created": 1315882338.0,
				"dest": "GavChap",
				"author": "gergtreble",
				"created_utc": 1315857138.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>All I want is collapsable comment trees! None of the (otherwise awesome) reddit apps can do this!</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jd0qi?context=3",
				"replies": "",
				"new": false,
				"id": "c2jd0qi",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "You know, I actually took it apart like a month ago to replace the power jack connector and I gave it a good clean out then, so I don't think that's the issue.  It's about 2-3 years old I think.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jd0jp",
				"created": 1315857105.0,
				"dest": "GavChap",
				"author": "WinstonKennedy",
				"created_utc": 1315857105.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>You know, I actually took it apart like a month ago to replace the power jack connector and I gave it a good clean out then, so I don't think that's the issue.  It's about 2-3 years old I think.</p></div><!-- SC_ON -->",
				"subreddit": "techsupport",
				"parent_id": 26274831745,
				"context": "/r/techsupport/comments/kd6t7/laptop_gone_diedpossible_os_problem/c2jd0jp?context=3",
				"replies": "",
				"new": false,
				"id": "c2jd0jp",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "I know what he means.  I thought the same thing.\n\n\nFirst off....AWESOME JOB!  Clearly the front runner in reddit clients.\n\nNow to clarify\n\nIn the email app you've got 3 panes. \n\n1. Folders \n\n2. Headers\n\n3. Messages\n\nYou can completely hide any of these panes.  For example, when I open the email app I just see headers and emails.  Also, I can still read the entire header.\n\nIn your app when I click on a post, all the other posts and subreddits are slightly hidden.  \n\nI would rather be able to hide the subreddits and just browse the front page and have the links open on the right without having to constantly resize the panes.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jcz73",
				"created": 1315882038.0,
				"dest": "GavChap",
				"author": "JavaLSU",
				"created_utc": 1315856838.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>I know what he means.  I thought the same thing.</p>\n\n<p>First off....AWESOME JOB!  Clearly the front runner in reddit clients.</p>\n\n<p>Now to clarify</p>\n\n<p>In the email app you've got 3 panes.</p>\n\n<ol>\n<li><p>Folders</p></li>\n<li><p>Headers</p></li>\n<li><p>Messages</p></li>\n</ol>\n\n\n<p>You can completely hide any of these panes.  For example, when I open the email app I just see headers and emails.  Also, I can still read the entire header.</p>\n\n<p>In your app when I click on a post, all the other posts and subreddits are slightly hidden.</p>\n\n<p>I would rather be able to hide the subreddits and just browse the front page and have the links open on the right without having to constantly resize the panes.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274834673,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jcz73?context=3",
				"replies": "",
				"new": false,
				"id": "c2jcz73",
				"subject": "comment reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Good work mate! Looking really good so far. A few suggestions to improve the user interface:\n\n\nMove \"Home\" to the subreddit list.\n\n\nInstead of showing the current subreddit at the top, just highlight the selected reddit on the list.\n\n\nMove the login button either to the top of the subreddit list or to the bottom bar where you also have the refresh. \n\n\nBy doing all of the above you've effectively gained more screen real state for the actual content.\n\n\nOther than that, I would allow the different panes to actually close same way as you would with the email program.\n\n\nOther than that, it's fantastic. Congratulation again.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jcsxh",
				"created": 1315855638.0,
				"dest": "GavChap",
				"author": "mefm247",
				"created_utc": 1315855638.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Good work mate! Looking really good so far. A few suggestions to improve the user interface:</p>\n\n<p>Move \"Home\" to the subreddit list.</p>\n\n<p>Instead of showing the current subreddit at the top, just highlight the selected reddit on the list.</p>\n\n<p>Move the login button either to the top of the subreddit list or to the bottom bar where you also have the refresh.</p>\n\n<p>By doing all of the above you've effectively gained more screen real state for the actual content.</p>\n\n<p>Other than that, I would allow the different panes to actually close same way as you would with the email program.</p>\n\n<p>Other than that, it's fantastic. Congratulation again.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jcsxh?context=3",
				"replies": "",
				"new": false,
				"id": "c2jcsxh",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Screenshots?  My TP doesn't get here until Wednesday.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jcl4x",
				"created": 1315879343.0,
				"dest": "GavChap",
				"author": "bbene",
				"created_utc": 1315854143.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Screenshots?  My TP doesn't get here until Wednesday.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jcl4x?context=3",
				"replies": "",
				"new": false,
				"id": "c2jcl4x",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "You win the best reddit client for webos award.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jch75",
				"created": 1315878598.0,
				"dest": "GavChap",
				"author": "ebonwumon",
				"created_utc": 1315853398.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>You win the best reddit client for webos award.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jch75?context=3",
				"replies": "",
				"new": false,
				"id": "c2jch75",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Oh my god it's beautiful.",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jcen8",
				"created": 1315878103.0,
				"dest": "GavChap",
				"author": "Red-Sox",
				"created_utc": 1315852903.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Oh my god it's beautiful.</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": null,
				"context": "/r/webos/comments/kdadw/behold_my_reddit_reader_app/c2jcen8?context=3",
				"replies": "",
				"new": false,
				"id": "c2jcen8",
				"subject": "post reply"
			}
		},
		{
			"kind": "t1",
			"data": {
				"body": "Oh, I'm mistaken about the language android applications are done in. I think the bulk of my post can be disregarded then. Sorry! ",
				"was_comment": true,
				"first_message": null,
				"name": "t1_c2jah19",
				"created": 1315838171.0,
				"dest": "GavChap",
				"author": "diamond_dobby",
				"created_utc": 1315838171.0,
				"body_html": "<!-- SC_OFF --><div class=\"md\"><p>Oh, I'm mistaken about the language android applications are done in. I think the bulk of my post can be disregarded then. Sorry!</p></div><!-- SC_ON -->",
				"subreddit": "webos",
				"parent_id": 26274716837,
				"context": "/r/webos/comments/kd2hz/is_it_fundamentally_possible_for_a_buyer_of_webos/c2jah19?context=3",
				"replies": "",
				"new": false,
				"id": "c2jah19",
				"subject": "comment reply"
			}
		}],
		"after": "t1_c2jah19",
		"before": null
	}
}